### ISSUE TITLE
fix the "import _imp" bug

### ISSUE THREAD

**Issue by globau** [globau/mozreview-devenv#11]

**Comment by globau** [comment]
this only appears when pushing; other rb functionality works without issue.
i suspect it's a weird interaction with mercurial's dymanic module loader.

stacktrace:

```
~/dev/mozrev...p/dev/test-repo$ hg push
pushing to ssh://hgrb/test-repo
searching for changes
no changes found
submitting 1 changesets for review
remote: Traceback (most recent call last):
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/dispatch.py", line 191, in _runcatch
remote:     return _dispatch(req)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/dispatch.py", line 924, in _dispatch
remote:     cmdpats, cmdoptions)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/dispatch.py", line 681, in runcommand
remote:     ret = _runcommand(ui, options, cmd, d)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/dispatch.py", line 1055, in _runcommand
remote:     return checkargs()
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/dispatch.py", line 1015, in checkargs
remote:     return cmdfunc()
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/dispatch.py", line 921, in <lambda>
remote:     d = lambda: util.checksignature(func)(ui, *args, **cmdoptions)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/util.py", line 991, in check
remote:     return func(*args, **kwargs)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/commands.py", line 6244, in serve
remote:     s.serve_forever()
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/sshserver.py", line 103, in serve_forever
remote:     while self.serve_one():
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/sshserver.py", line 121, in serve_one
remote:     rsp = wireproto.dispatch(self.repo, self, cmd)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/wireproto.py", line 481, in dispatch
remote:     return func(repo, proto, *args)
remote:   File "/src/hgext/reviewboard/hgrb/proto.py", line 186, in pushreviewwireprotocommand
remote:     res = _processpushreview(repo, req, ldap_username)
remote:   File "/src/hgext/reviewboard/hgrb/proto.py", line 319, in _processpushreview
remote:     apikey=bzapikey)
remote:   File "/src/hgext/reviewboard/hgrb/proto.py", line 139, in associate_ldap_username
remote:     from reviewboardmods.pushhooks import associate_ldap_username as alu
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 141, in _demandimport
remote:     return _hgextimport(_import, name, globals, locals, fromlist, level)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 53, in _hgextimport
remote:     return importfunc(name, globals, *args, **kwargs)
remote:   File "/src/pylib/reviewboardmods/reviewboardmods/pushhooks.py", line 11, in <module>
remote:     from rbtools.api.client import RBClient
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 217, in _demandimport
remote:     mod = _hgextimport(_origimport, name, globals, locals)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 53, in _hgextimport
remote:     return importfunc(name, globals, *args, **kwargs)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/rbtools/api/client.py", line 5, in <module>
remote:     from rbtools.api.transport.sync import SyncTransport
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 217, in _demandimport
remote:     mod = _hgextimport(_origimport, name, globals, locals)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 53, in _hgextimport
remote:     return importfunc(name, globals, *args, **kwargs)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/rbtools/api/transport/sync.py", line 4, in <module>
remote:     from rbtools.api.factory import create_resource
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 217, in _demandimport
remote:     mod = _hgextimport(_origimport, name, globals, locals)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 53, in _hgextimport
remote:     return importfunc(name, globals, *args, **kwargs)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/rbtools/api/factory.py", line 3, in <module>
remote:     from rbtools.api.resource import (CountResource, ItemResource,
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 217, in _demandimport
remote:     mod = _hgextimport(_origimport, name, globals, locals)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 53, in _hgextimport
remote:     return importfunc(name, globals, *args, **kwargs)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/rbtools/api/resource.py", line 6, in <module>
remote:     from pkg_resources import parse_version
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 217, in _demandimport
remote:     mod = _hgextimport(_origimport, name, globals, locals)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 53, in _hgextimport
remote:     return importfunc(name, globals, *args, **kwargs)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3138, in <module>
remote:     @_call_aside
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3124, in _call_aside
remote:     f(*args, **kwargs)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3163, in _initialize_master_working_set
remote:     add_activation_listener(lambda dist: dist.activate())
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 975, in subscribe
remote:     callback(dist)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3163, in <lambda>
remote:     add_activation_listener(lambda dist: dist.activate())
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2663, in activate
remote:     fixup_namespace_packages(self.location)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2243, in fixup_namespace_packages
remote:     _imp.acquire_lock()
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 130, in __getattribute__
remote:     self._load()
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 96, in _load
remote:     mod = _hgextimport(_import, head, globals, locals, None, level)
remote:   File "/src/dev/venv/lib64/python2.7/site-packages/mercurial/demandimport.py", line 53, in _hgextimport
remote:     return importfunc(name, globals, *args, **kwargs)
remote: ImportError: No module named _imp
remote: abort: No module named _imp!
abort: unexpected response: empty string
~/dev/mozrev...p/dev/test-repo$
```

it appears that just using _imp immediately after it is imported is enough to fix it - eg. acquiring then releasing a lock.

../python2.7/site-packages/pkg_resources/__init__.py:

```
try:
    import _imp
    _imp.acquire_lock()
    _imp.release_lock()
except ImportError as ex:
    # Python 3.2 compatibility
    import imp as _imp
```

**Comment by indygreg** [comment]
I triggered this by upgrading pip+setuptools. See also https://bugzilla.mozilla.org/show_bug.cgi?id=1243501

**Comment by globau** [comment]
https://www.mercurial-scm.org/pipermail/mercurial-devel/2016-February/079957.html
