### ISSUE TITLE
clean provisioning fails: Permission matching query does not exist

### ISSUE THREAD

**Issue by globau** [globau/mozreview-devenv#17]
```
TASK: [review-board | configure review board] *********************************
failed: [default] => {"changed": true, "cmd": ["/venv/bin/python", "/reviewboard/install-reviewboard.py", "--bugzilla_port=9081"], "delta": "0:00:04.708623", "end": "2016-02-09 14:08:30.822523", "rc": 1, "start": "2016-02-09 14:08:26.113900", "warnings": []}
stderr: Traceback (most recent call last):
  File "/reviewboard/install-reviewboard.py", line 114, in <module>
    verify_perm = Permission.objects.get(codename='verify_diffset')
  File "/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/venv/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
django.contrib.auth.models.DoesNotExist: Permission matching query does not exist.'
```

at this line:

```
verify_perm = Permission.objects.get(codename='verify_diffset')
```

looks like we need to for more initialisation of the mozreview extension before we can create that user.

**Comment by globau** [comment]
or make sure your vct clone includes the changes that added verify_diffset
